version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./app:/app
      - static_volume:/app/static
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --no-input &&
             python3 manage.py wait_for_db &&
             python3 manage.py create_admin &&
             python3 manage.py driver_test &&
             gunicorn scanerr.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./env/.env.prod
    volumes: 
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A scanerr worker --beat --scheduler django --loglevel=info
    volumes:
      - ./app:/scanerr
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
      - redis
      - app

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    depends_on:
      - app
    volumes:
      - static_volume:/app/static

volumes:
  pgdata:
  static_volume: