services:
  

  app:
    container_name: cursion-app
    hostname: cursion-app
    platform: linux/amd64
    privileged: true
    restart: always
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ["/entrypoint.sh", "app", "local"]
    env_file:
      - ./env/.env.local
    volumes:
      - app:/app
    depends_on:
      - db


  db:
    container_name: cursion-db
    hostname: cursion-db
    image:  postgres:14-alpine
    env_file:
      - ./env/.env.local
    volumes: 
      - pgdata:/var/lib/postgresql/data
  

  redis:
    container_name: cursion-redis
    hostname: cursion-redis
    image: redis:alpine
    ports:
      - "6379"


  celery:
    container_name: cursion-celery
    hostname: cursion-celery
    platform: linux/amd64
    privileged: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh", "celery"]
    volumes:
      - celery:/app
    env_file:
      - ./env/.env.local
    depends_on:
      - redis
      - app
      - db


  beat:
    container_name: cursion-beat
    hostname: cursion-beat
    platform: linux/amd64
    privileged: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh", "beat"]
    volumes:
      - beat:/app
    env_file:
      - ./env/.env.local
    depends_on:
      - redis
      - celery
      - app
      - db


  yellowlab:
    container_name: yellowlab
    hostname: yellowlab
    privileged: true
    restart: always
    image: cursion/ylt
    ports:
      - 8383:8383
    depends_on:
      - redis
      - celery 
      - app
      - db


volumes:
  pgdata:
  app:
  celery:
  beat:
