


services:
  
  app:
    container_name: scanerr-app
    hostname: scanerr-app
    privileged: true
    init: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    entrypoint: ["/local-entrypoint.sh", "app"]
    env_file:
      - ./env/.env.stage
  


  redis:
    image: redis:alpine
    ports:
      - "6379"
  


  celery:
    container_name: scanerr-celery
    hostname: scanerr-celery
    privileged: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    entrypoint: ["/local-entrypoint.sh", "celery"]
    volumes:
      - ./app:/scanerr
    env_file:
      - ./env/.env.stage
    depends_on:
      - redis
      - app
