name: cursion
services:
  

  server:
    container_name: cursion-server
    hostname: cursion-server
    platform: linux/amd64
    privileged: true
    init: true
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ["/entrypoint.sh", "server", "stage"]
    env_file:
      - ./env/.env.stage
    volumes:
      - ./app:/app
