services:
  

  app:
    container_name: cursion-app
    hostname: cursion-app
    platform: linux/amd64
    privileged: true
    init: true
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ["/entrypoint.sh", "app", "stage"]
    env_file:
      - ./env/.env.stage
    volumes:
      - ./app:/app
