apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      containers:
        - name: beat
          image: cursiondev/server:latest
          imagePullPolicy: IfNotPresent
          command: ["/entrypoint.sh", "beat"]
          envFrom:
            - configMapRef:
                name: app-configs
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"

