apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  ## ensure below section is commented out on first creation ##
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-nginx     
  name: app-ingress
spec:
  ## ensure below section is comented out on first creation ##
  tls:
    - hosts:
      - api2.scanerr.io
      secretName: letsencrypt-nginx
  rules:
  - host: api2.scanerr.io
    http:
      paths:
      - backend:
          service:
            name: app-service
            port:
              number: 80
        path: /
        pathType: Prefix
  ingressClassName: nginx