apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-scaler
spec:
  scaleTargetRef:
    name: celery-deployment
  pollingInterval: 3
  minReplicaCount: 2
  maxReplicaCount: 30
  triggers:
    - type: redis
      metadata:
        address: redis:6379 # Format must be host:port
        listName: celery # Required
        listLength: "5" # Required
        activationListLength: "5" # optional
        enableTLS: "false" # optional
        unsafeSsl: "false" # optional
        databaseIndex: "0" # optional
