apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      restartPolicy: Always
      containers:
        - image: rabbitmq:alpine
          name: rabbitmq
          ports:
            - containerPort: 5672
          resources: 
            limits:
              cpu: "250m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
status: {}



---

apiVersion: v1
kind: Service
metadata:  
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    service: rabbitmq

