# Generated by Django 3.2.3 on 2023-07-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='time_crawl',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
